In [1]:
# import dependencies
import numpy as np

## Data Types and Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [13]:
#MultiDimensional Arrays- Matrices

a2 = np.array([[1, 2.0, 3.3],
       [ 4, 5, 6.5]])
a3 = np.array([[[1,2,3],
        [4,5,6],
       [7,8,9]],
      [[10,11,12],
      [13,14,15],
      [16,17,18]]])

In [14]:
a2.shape

(2, 3)

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a3.shape

(2, 3, 3)

In [17]:
# check dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [19]:
# check data types
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [20]:
# check size to learn number of entries
a1.size, a2.size, a3.size

(3, 6, 18)

In [23]:
# Create dataframe from np array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Array 

In [26]:
# use shift + tab to bring up doc string...
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# default with zeros
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
range_array = np.arange(0, 100, 4)
range_array

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [34]:
# populate with random default values
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[4, 3, 1, 5, 7],
       [9, 7, 3, 4, 6],
       [4, 2, 3, 2, 2]])

In [35]:
# random_array2 uses size argument to fill with decimals
random_array2 = np.random.random((5,3))
random_array2

array([[0.33447532, 0.55898191, 0.3383639 ],
       [0.03664836, 0.60159263, 0.07253349],
       [0.93498225, 0.0247685 , 0.30271464],
       [0.53095918, 0.9935754 , 0.87088973],
       [0.71362302, 0.06874822, 0.12105282]])

In [37]:
random_df = pd.DataFrame(random_array2)
random_df

0         1         2
0  0.334475  0.558982  0.338364
1  0.036648  0.601593  0.072533
2  0.934982  0.024769  0.302715
3  0.530959  0.993575  0.870890
4  0.713623  0.068748  0.121053

In [45]:
# Pseudo Random
# use random seed to get reproducible random values
np.random.seed(103)
random_array3 = np.random.randint(23,size=(4,4))
random_array3

array([[ 7,  9, 19,  6],
       [17, 21, 12, 11],
       [12, 20, 13,  6],
       [13,  1, 10, 20]])